export const generateIdCardHTML = (data: any) => {
  return `
     <html>
          <head>
            <title>Print ID Card</title>
            <link rel="stylesheet" type="text/css" href="/styles/print.css">
            <style>
              .content {
                width: 3.375in;
                height: 2.13in;
                margin-left: auto;
                margin-right: auto;
                border: 1px solid #99a1af;
              }

              .top_watermark {
                width: 100%;
                height: 60px;
                overflow: hidden;
                display: flex;
                position: relative;
                justify-content: space-between;
                gap: 7px;
                padding-top: 12px;
                padding-bottom: 8px;
                padding-inline: 20px;
              }

              .img_top {
                position: relative;
                width: 40px;
                height: 40px;
              }
              .title1 {
                color: oklch(0.527 0.154 150.069);
                font-size: 1.2rem;
                font-weight: 800;
                line-height: 16px;
              }
              .title2 {
                color: oklch(0.527 0.154 150.069);
                font-size: 0.9rem;
                font-weight: 800;
                line-height: 16px;
              }
              .subtext {
                font-size: 5.4px;
                font-weight: 700;
                line-height: 8px;
              }
              .smalltext1 {
                font-size: 0.5rem;
                font-weight: 700;
                line-height: 10px;
              }
              .smalltext {
                font-size: 7px;
                line-height: 10px;
              }

              .nin_text {
                font-size: 5.5px;
                line-height: 10px;
              }

              .nin_text2 {
                font-size: 6.5px;
                font-weight: 700;
                line-height: 7px;
              }

              .name_text {
                font-size: 7px;
                line-height: 0;
              }

              .name_text2 {
                font-size: 0.8rem;
                font-weight: 700;
                line-height: 20px;
              }

              .box {
                display: flex;
                gap: 20px;
                margin-bottom: 4px;
              }

              .w_55 {
                width: 55px;
              }

              .first_grid {
                flex: 0.9;
                position: relative;
                z-index: 50;
              }

              .second_grid {
                flex: 1.9;
                position: relative;
                z-index: 50;
              }

              .third_grid {
                flex: 0.8;
                height: min-content;
                position: relative;
                z-index: 50;
                align-self: flex-end;
              }

              .ASLG {
                font-size: 7px;
                text-align: center;
                line-height: 10px;
              }

              .blur_image {
                position: absolute;
                width: 120px;
                height: 110px;
                margin: auto;
                right: 70px;
                top: 10px;
                opacity: 15%;
              }
              .bov_text {
                font-size: 6px;
                text-align: center;
              }

              .txtzz {
                font-size: 9px;
                font-weight: 700;
                line-height: 10px;
              }

              .first_img_grid {
                position: relative;
                width: 100%;
                height: 90px;
                margin-bottom: 4px;
              }

              .qrcode {
                width: 100%;
                height: 50px;
                position: relative;
              }

              .line1 {
                width: 100%;
                height: 2px;
                background-color: oklch(0.723 0.219 149.579);
              }

              .line2 {
              width: 100%;
              height: 2px;
              background-color: oklch(0.905 0.182 98.111);
              }


              .bottom_watermark {
                height: 140px;
                width: 100%;
                overflow: hidden;
                position: relative;
                gap: 10px;
                vertical-align: bottom;
                display: flex;
                padding-block: 12px;
                padding-inline: 10px;
              }

              .top_watermark::after {
                content: "ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ";
                color: green;
                font-size: 0.2rem;
                position: absolute;
                font-weight: bolder;
                line-height: 4px;
                opacity: 0.2;
                transform: rotate(310deg);
                width: 250px;
                height: 20px;
                text-wrap: wrap;
                top: -20px;
                left: -20px;
              }
                            .bottom_watermark::before {
                content: "ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ";
                color: green;
                font-size: 3px;
                position: absolute;
                font-weight: bolder;
                line-height: 4.5px;
                opacity: 0.3;
                transform: rotate(320deg);
                width: 350px;
                height: 40px;
                text-wrap: wrap;
                left: -180px;
              }

              .bottom_watermark::after {
                content: "ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ABEOKUTA SOUTH LOCAL GOVERNMENT ";
                color: green;
                font-size: 3px;
                position: absolute;
                font-weight: bolder;
                line-height: 4.5px;
                opacity: 0.3;
                transform: rotate(310deg);
                width: 320px;
                height: 30px;
                text-wrap: wrap;
                right: -40px;
                bottom: 60px;
              }
            </style>
          </head>
          <body>
      <div class="id-card">
        <div class="top-watermark">
          <div class="img-top">
            <img src="/images/identification/abeokuta_logo.png" alt="logo image" />
          </div>
          <div>
            <h1 class="title1">${data.localGovt}</h1>
            <h1 class="title2">${data.localGovtSub}</h1>
            <h6 class="subtext">${data.address}</h6>
          </div>
          <div class="img-top">
            <img src="/images/identification/abeokuta_logo.png" alt="logo image" />
          </div>
        </div>
        <div class="line1"></div>
        <div class="line2"></div>
  
        <div class="bottom-watermark">
          <div class="first-grid">
            <div class="first-img-grid">
              <img src="${data.photo}" alt="profile photo" />
            </div>
            <div>
              <div class="nin-text">NIN / BVN</div>
              <div class="nin-text2">${data.nin}</div>
            </div>
          </div>
  
          <div class="second-grid">
            <div>
              <div class="name-text">Name</div>
              <div class="name-text2">${data.name}</div>
            </div>
            <div class="mb-1">
              <div class="smalltext">Address</div>
              <div class="txtzz">${data.residence}</div>
            </div>
            <div class="box">
              <div class="w-55">
                <div class="smalltext">Date of Birth</div>
                <div class="smalltext1">${data.dob}</div>
              </div>
              <div>
                <div class="smalltext">Emergency Contact</div>
                <div class="smalltext1">${data.contact}</div>
              </div>
            </div>
  
            <div class="box">
              <div class="w-55">
                <div class="smalltext">Branch</div>
                <div class="smalltext1">${data.branch}</div>
              </div>
              <div>
                <div class="smalltext">Plate Number</div>
                <div class="smalltext1">${data.plateNumber}</div>
              </div>
            </div>
  
            <div class="box">
              <div class="w-55">
                <div class="smalltext">Unit</div>
                <div class="smalltext1">${data.unit}</div>
              </div>
              <div>
                <div class="smalltext">Union Name</div>
                <div class="smalltext1">${data.union}</div>
              </div>
            </div>
          </div>
  
          <div class="third-grid">
            <div class="ASLG">ASLG</div>
            <div class="qrcode">
              <img src="${data.qrCode}" alt="QR Code" />
            </div>
            <div class="bov-text">
              COLOR (BIKE): <span style="font-weight: 700">${data.bikeColor}</span>
            </div>
          </div>
  
          <div class="blur-image">
            <img src="/images/identification/abeokuta_logo.png" alt="background watermark" />
          </div>
        </div>
      </div>
        <script>
            window.onload = function() { window.print(); }
          </script>
    </body>
  </html>
    `;
};
